version: "3"
services:
  app:
    tty: true
    restart: always
    build: ./
    volumes:
      - ./frontend:/opt/frontend
      - ./backend:/opt/backend
    ports:
      - "80:8080"
      - "3000:3000"
